sudo: false
rvm:
 - 2.1.8
 - 2.2.4
 - 2.3.0
script : bundle exec rake test
bundler_args: ""
gemfile:
  - gemfiles/rails3.2.gemfile
  - gemfiles/rails4.1.gemfile
  - gemfiles/rails4.2.gemfile
  - gemfiles/rails5.0.gemfile
cache: bundler
branches:
  only: master
matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails5.0.gemfile
