name: Continuous Integration
on:
  push:
    branches: [master]
  pull_request:
jobs:
  main:
    name: Specs
    runs-on: [ubuntu-latest]
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RAILS_ENV: test
    strategy:
      fail-fast: false
      matrix:
        rvm:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
        gemfile:
          - gemfiles/rails6.0.gemfile # Default
          - gemfiles/rails6.1.gemfile
          - gemfiles/rails7.0.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rvm }}
          bundler-cache: true
      - run: bundle exec rake test
