name: Continuous Integration
on:
  push:
    branches: master
  pull_request:
jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      BUNDLE_GEMFILE: ${{ matrix.gemfile }}
      RAILS_ENV: test
    strategy:
      fail-fast: false
      matrix:
        rvm:
          - '3.1'
          - '3.2'
        gemfile:
          - gemfiles/mail2.7.gemfile
          - gemfiles/rails6.1.gemfile
          - gemfiles/rails7.0.gemfile
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rvm }}
          bundler-cache: true
      - run: bundle exec rake test

  tests_successful:
    name: Tests passing?
    needs: tests
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: |
          if ${{ needs.tests.result == 'success' }}
          then
            echo "All tests pass"
          else
            echo "Some tests failed"
            false
          fi
