name: Test against Rails main

on:
  schedule:
    - cron: "0 0 * * *" # Run every day at 00:00 UTC
  workflow_dispatch:
  push:

jobs:
  main:
    name: Specs
    runs-on: [ubuntu-latest]
    env:
      BUNDLE_GEMFILE: gemfiles/rails_main.gemfile
      RAILS_ENV: test
    strategy:
      fail-fast: false
      matrix:
        rvm:
          - '3.3'
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.rvm }}
          bundler-cache: true
      - run: bundle exec rake test
